---
- tags: bosch__azure-cli
  block:
    - import_role:
        name: azure-cli

    - slurp:
        src: /usr/lib64/az/lib/python3.6/site-packages/certifi/cacert.pem
      register: _cacert

    - become: True
      file:
        state: directory
        path: /usr/local/lib64/az/lib/python3.6/site-packages/certifi

    - become: True
      copy:
        dest: /usr/local/lib64/az/lib/python3.6/site-packages/certifi/cacert.pem
        content: |
          {{ _cacert['content'] | b64decode }}
          {{ lookup('file', 'BOSCH-CA_DE.pem') }}

    - become: True
      lineinfile:
        dest: /etc/environment
        regex: "^{{ item.key }}="
        line: "{{ item.key }}={{ item.value }}"
      with_dict:
        REQUESTS_CA_BUNDLE: /usr/local/lib64/az/lib/python3.6/site-packages/certifi/cacert.pem
