---
- hosts: localhost
  connection: local
  vars:
    ansible_python_interpreter: "{{ ansible_playbook_python }}"
  module_defaults:
    copy:
      backup: True
    ini_file:
      backup: True
  roles:
    - role: aws
#    - name: bosch__azure-cli
#    - name: rpmdevtools
