---
- hosts: localhost
  connection: local
  vars:
    ansible_python_interpreter: "{{ ansible_playbook_python }}"
  module_defaults:
    copy:
      backup: True
    ini_file:
      backup: True
  roles:
    - role: aws
#    - name: bosch__azure-cli
#    - name: rpmdevtools
  tasks:
    - become: True
      blockinfile:
        dest: /etc/pki/tls/certs/ca-bundle.crt
        block: "{{ lookup('file', 'BOSCH-CA_DE.pem') }}"

    - become: True
      blockinfile:
        dest: /usr/lib/python3.7/site-packages/botocore/cacert.pem
        block: "{{ lookup('file', 'BOSCH-CA_DE.pem') }}"
    - become: True
      blockinfile:
        dest: /usr/lib/python3.7/site-packages/boto/cacerts/cacerts.txt
        block: "{{ lookup('file', 'BOSCH-CA_DE.pem') }}"
#    - become: True
#      blockinfile:
#        dest: /usr/lib/python3.7/site-packages/botocore/vendored/requests/cacert.pem
#        block: "{{ lookup('file', 'BOSCH-CA_DE.pem') }}"
    - become: True
      tags: extdep
      dnf:
        name:
          - patch
    - become: True
      patch:
        dest: /usr/lib/python3.7/site-packages/boto/connection.py
        src: boto_connection.patch
    - become: True
      tags: extdep
      dnf:
        name:
          - certbot-dns-route53
