---
- hosts: localhost
  connection: local
  vars:
    ansible_python_interpreter: "{{ ansible_playbook_python }}"
  roles:
    - role: aws
    - name: bosch__azure-cli
  tasks:
    - become: True
      blockinfile:
        dest: /etc/pki/tls/certs/ca-bundle.crt
        block: "{{ lookup('file', 'BOSCH-CA_DE.pem') }}"
    - become: True
      blockinfile:
        dest: /usr/lib/python3.7/site-packages/botocore/cacert.pem
        block: "{{ lookup('file', 'BOSCH-CA_DE.pem') }}"
    - become: True
      blockinfile:
        dest: /usr/lib/python3.7/site-packages/boto/cacerts/cacerts.txt
        block: "{{ lookup('file', 'BOSCH-CA_DE.pem') }}"
    - become: True
      blockinfile:
        dest: /usr/lib/python3.7/site-packages/botocore/vendored/requests/cacert.pem
        block: "{{ lookup('file', 'BOSCH-CA_DE.pem') }}"
    - become: True
      dnf:
        name:
          - patch
    - become: True
      patch:
        dest: /usr/lib/python3.7/site-packages/boto/connection.py
        src: boto_connection.patch
