#! /usr/bin/ansible-playbook
---
- hosts: localhost
  connection: local
  vars:
    ansible_python_interpreter: "{{ ansible_playbook_python }}"
  module_defaults:
    copy:
      backup: True
    ini_file:
      backup: True
  roles:
    - role: aws
    - name: azure-cli
    - name: rpmdevtools
  tasks:
    - name: Enable Fedora Copr for mmu-dist-rpms
      become: True
      command:
        cmd: dnf copr enable -y mmu/mmu-dist-rpms
        creates: /etc/yum.repos.d/_copr:copr.fedorainfracloud.org:mmu:mmu-dist-rpms.repo
        warn: False

    - become: True
      tags: extdep
      dnf:
        name:
          - terraform-dist
          - packer-dist
