#! /usr/bin/ansible-playbook -i localhost,
---

- hosts: localhost
  connection: local
  vars:
    ansible_python_interpreter: "{{ ansible_playbook_python }}"
  module_defaults:
    copy:
      backup: True
    ini_file:
      backup: True
  roles:
    - name: cntlm
