---
# vi:ai:et:sw=2:ts=2

- hosts: localhost
  connection: local
  module_defaults:
    copy:
      backup: True
    ini_file:
      backup: True
  roles:
    #- name: proxy
    - name: cntlm
    - name: cloudflared-proxy-dns
