---
# vi:ai:et:sw=2:ts=2

- hosts: localhost
  connection: local
  module_defaults:
    copy:
      backup: True
  roles:
    #- name: proxy
    #- name: cntlm
    - name: cloudflared-proxy-dns
    #- name: bosch__azure-cli
  tasks:
    - become: True
      blockinfile:
        dest: /etc/pki/tls/certs/ca-bundle.crt
        block: "{{ lookup('file', 'BOSCH-CA_DE.pem') }}"
    - become: True
      patch:
        path: /usr/lib/python3.7/site-packages/boto/connection.py
        patch: boto_connection.patch
