---
# vi:ai:et:sw=2:ts=2

- hosts: localhost
  connection: local
  become: True
  tasks:
    - user:
        name: "{{ ansible_env.SUDO_USER }}"
        groups: vboxsf
        append: yes
      when: ansible_virtualization_type == 'virtualbox'
    - copy:
        dest: /etc/locale.conf 
        content: |
          LANG=C
    - timezone:
        name: Europe/Berlin
    - dnf:
        name:
          - git
          - tig
          - awscli
          - python3-boto3
          - python3-dns
          - xsel
          - parcellite
          - vim
          - vim-X11
          - rcs
          - pandoc
          - rpmdevtools
          - mock
          - rpkg
          - jq
    - user:
        name: "{{ ansible_env.SUDO_USER }}"
        groups: mock
        append: yes

- hosts: localhost
  connection: local
  tasks:
