---
# vi:ai:et:sw=2:ts=2

- hosts: localhost
  connection: local
  become: True
  tasks:
    - user:
        name: "{{ ansible_env.SUDO_USER }}"
        groups: vboxsf
        append: yes
      when: ansible_virtualization_type == 'virtualbox'
    - copy:
        dest: /etc/locale.conf 
        content: |
          LANG=C
    - dnf:
        name:
          - git
          - tig
          - rcs
          - pandoc
          - jq
- hosts: localhost
  connection: local
  tasks:
