#! /usr/bin/ansible-playbook
---

- hosts: localhost
  connection: local
  vars:
    ansible_python_interpreter: "{{ ansible_playbook_python }}"
  tasks:
    - become: True
      dnf:
        name:
          - ruby-devel
          - rubygem-bundler
