---
# vi:ai:et:sw=2:ts=2
#
- hosts: localhost
  connection: local
  become: True
  become_flags: '-i'
  tags: root
  vars:
    ansible_python_interpreter: /usr/bin/python3
  tasks:
    - user:
        name: muenchm
        groups: vboxsf
        append: yes

    - dnf:
        name:
          - git
          - tig
          - acpid
          - clipit
          - "https://www.dropbox.com/download?dl=packages/fedora/nautilus-dropbox-2018.11.28-1.fedora.x86_64.rpm"
          - python2-boto
          - python2-boto3
          - python-netaddr
          - python-dnspython
          - python2-dns
          - youtube-dl
          - vim
          - perl-Text-Markdown
          - xdotool
          - pandoc
          - libselinux-python
          - xsel
          - tidy
          - firefox
          - thunderbird
          - pinentry-qt
          - vim-X11
          - jq
          - graphviz
          - okular
          - NetworkManager-openvpn
          - certbot
          - python3-certbot-dns-route53

    - systemd:
        name: acpid
        enabled: True
        state: started

    - selinux:
        state: permissive
        policy: targeted

    - pip:
        name: grip
