---
# vi:ai:et:sw=2:ts=2
#
- hosts: localhost
  connection: local
  become: yes
  tasks:
    - package:
        name: "{{ item }}"
      with_items:
        - acpid
        - clipit
        - "https://www.dropbox.com/download?dl=packages/fedora/nautilus-dropbox-2015.10.28-1.fedora.x86_64.rpm"
