---
# vi:ai:et:sw=2:ts=2
#
- hosts: localhost
  connection: local
  become: yes
  tags: [ 'root' ]
  tasks:
    - package:
        name: "{{ item }}"
      with_items:
        - acpid
        - clipit
        - "https://www.dropbox.com/download?dl=packages/fedora/nautilus-dropbox-2015.10.28-1.fedora.x86_64.rpm"
        - python2-boto
        - python-netaddr
        - python2-dns
        - youtube-dl
        - vim
        - perl-Text-Markdown
        - xdotool
        - awscli
        - pandoc
        - libselinux-python

    - selinux: state=disabled

    - pip:
        name: grip

#    - name: awscli archive
#      unarchive:
#        src: "https://s3.amazonaws.com/aws-cli/awscli-bundle.zip"
#        dest: /tmp
#        copy: no
#
#    - name: awscli installation
#      become: yes
#      shell: "./awscli-bundle/install -i /usr/local/aws -b /usr/local/bin/aws"
#      args:
#        chdir: /tmp

    - alternatives:
        link: /usr/bin/x-www-browser
        name: x-www-browser
        path: /usr/bin/firefox
        priority: 100

    - alternatives:
        link: /usr/bin/gnome-www-browser
        name: gnome-www-browser
        path: /usr/bin/firefox
        priority: 100

- hosts: localhost
  connection: local
  tasks:
    - copy:
        dest: ~/.Xdefaults
        content: |
          URxvt.font: 10x20
    - file:
        dest: "{{ item }}"
        state: directory
      with_items:
        - ~/.vim
        - ~/.vim/autoload
        - ~/.vim/bundle
    - get_url:
        url: https://tpo.pe/pathogen.vim
        dest: ~/.vim/autoload/pathogen.vim
    - git:
        repo: git@github.com:dhruvasagar/vim-table-mode.git
        dest: ~/.vim/bundle/table-mode
    - git:
        repo: https://github.com/JamshedVesuna/vim-markdown-preview.git
        dest: ~/.vim/bundle/vim-markdown-preview
        accept_hostkey: yes
    - lineinfile:
        dest: ~/.vimrc
        line: "{{ item }}"
        create: yes
      with_items:
        - "execute pathogen#infect()"
        - "let vim_markdown_preview_browser='Mozilla Firefox'"
        - "let vim_markdown_preview_perl=1"
        - "let vim_markdown_preview_use_xdg_open=1"

