---
# vi:ai:et:sw=2:ts=2
#
- hosts: localhost
  connection: local
  become: True
  become_flags: '-i'
  tags: root
  vars:
    ansible_python_interpreter: /usr/bin/python3
  tasks:
    - user:
        name: muenchm
        groups: vboxsf
        append: yes

    - dnf:
        name:
          - git
          - tig
          - acpid
          - clipit
          - "https://www.dropbox.com/download?dl=packages/fedora/nautilus-dropbox-2018.11.28-1.fedora.x86_64.rpm"
          - python2-boto
          - python2-boto3
          - python-netaddr
          - python-dnspython
          - python2-dns
          - youtube-dl
          - vim
          - perl-Text-Markdown
          - xdotool
          - awscli
          - pandoc
          - libselinux-python
          - xsel
          - tidy
          - firefox
          - thunderbird
          - pinentry-qt
          - vim-X11
          - jq
          - graphviz
          - okular
          - rpmdevtools
          - NetworkManager-openvpn
          - certbot
          - python3-certbot-dns-route53

    - systemd:
        name: acpid
        enabled: True
        state: started

    - selinux:
        state: permissive
        policy: targeted

    - pip:
        name: grip

    - alternatives:
        link: /usr/bin/x-www-browser
        name: x-www-browser
        path: /usr/bin/firefox
        priority: 100

    - alternatives:
        link: /usr/bin/gnome-www-browser
        name: gnome-www-browser
        path: /usr/bin/firefox
        priority: 100

- hosts: localhost
  connection: local
  tasks:
    - copy:
        dest: ~/.Xdefaults
        content: |
          URxvt.font: -*-liberation mono-medium-r-*-*-*-120-100-100-*-*-iso8859-1
    - file:
        dest: "{{ item }}"
        state: directory
      with_items:
        - ~/.vim
        - ~/.vim/autoload
        - ~/.vim/bundle
    - get_url:
        url: https://tpo.pe/pathogen.vim
        dest: ~/.vim/autoload/pathogen.vim
    - git:
        repo: git@github.com:dhruvasagar/vim-table-mode.git
        dest: ~/.vim/bundle/table-mode
    - git:
        repo: https://github.com/JamshedVesuna/vim-markdown-preview.git
        dest: ~/.vim/bundle/vim-markdown-preview
        accept_hostkey: yes
    - lineinfile:
        dest: ~/.vimrc
        line: "{{ item }}"
        create: yes
      with_items:
        - "execute pathogen#infect()"
        - "let vim_markdown_preview_browser='Mozilla Firefox'"
        - "let vim_markdown_preview_perl=1"
        - "let vim_markdown_preview_use_xdg_open=1"
        - 'let g:table_mode_corner="|"'
    - copy:
        dest: ~/.bash/aws.rc
        content: |
          complete -C '/usr/bin/aws_completer' aws
