---
- tags: extdep
  become: True
  dnf:
    name:
      - git
      - git-subtree
      - tig
      - gh
      - glab

- copy:
    dest: ~/.bashrc.d/
    src: _bashrc.d/git.sh

- git_config:
    name: alias.st
    value: status -sb
    scope: global

- git_config:
    name: alias.dt
    value: difftool
    scope: global

- git_config:
    name: alias.cl
    value: clean -f -d
    scope: global

- git_config:
    name: alias.ad
    value: add -uv
    scope: global

- git_config:
    name: alias.ci
    value: commit
    scope: global

- git_config:
    name: alias.rb
    value: rebase -i
    scope: global

- git_config:
    name: alias.fe
    value: fetch --prune --tags
    scope: global

- git_config:
    name: alias.mg
    value: merge --ff-only
    scope: global

- git_config:
    name: alias.df
    value: diff --relative
    scope: global

- git_config:
    name: alias.dn
    value: diff --name-only
    scope: global

- git_config:
    name: alias.lg
    value: log --oneline
    scope: global

- git_config:
    name: alias.aa
    value: add -Av
    scope: global

- git_config:
    name: alias.pf
    value: push --force-with-lease
    scope: global

- git_config:
    name: user.name
    value: Mathias Muench
    scope: global

- git_config:
    name: credential.helper
    value: store
    scope: global

- git_config:
    name: user.email
    value: mathias.muench@mathias-muench.de
    scope: local
    repo: "{{ playbook_dir }}"

- file:
    path: ~/.config/git/
    state: directory

- copy:
    dest: ~/.config/git/ignore
    content: |
      .*.swp
      nohup.out
      *.vim
      .undodir
      .obsidian/

