---
- tags: extdep
  become: True
  dnf:
    name:
      - git
      - git-subtree
      - tig
      - gh
      - glab

- copy:
    dest: ~/.bashrc.d/
    src: _bashrc.d/git.sh

- copy:
    dest: ~/.config/
    src: _config/git
