---

- tags: extdep
  become: True
  dnf:
    name: vim

- lineinfile:
    path: ~/.tar-exclude
    create: True
    line: ./.vimrc

- blockinfile:
    path: ~/.vimrc
    create: True
    block: "{{ lookup('file', '_vimrc') }}"
    marker: '" {mark} _vimrc'

- lineinfile:
    path: ~/.tar-exclude
    create: True
    line: ./.vim

- file:
    state: directory
    path: ~/.vim/autoload

- get_url:
    url: https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
    dest: ~/.vim/autoload/plug.vim
