---

- tags: extdep
  become: True
  dnf:
    name:
      - nano-default-editor
    state: absent

- tags: extdep
  become: True
  dnf:
    name:
      - vim
      - vim-default-editor

- lineinfile:
    path: ~/.tar-exclude
    create: True
    line: ./.vimrc

- copy:
    dest: ~/.vimrc
    create: True
    src: _vimrc
    marker: '" {mark} _vimrc'

- lineinfile:
    path: ~/.tar-exclude
    create: True
    line: ./.vim

- file:
    state: directory
    path: ~/.vim/autoload

- get_url:
    url: https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
    dest: ~/.vim/autoload/plug.vim
