---

- become: True
  yum_repository:
    name: copr:copr.fedorainfracloud.org:mmu:credstash-rpm
    description: Copr repo for credstash-rpm owned by mmu
    baseurl: https://copr-be.cloud.fedoraproject.org/results/mmu/credstash-rpm/fedora-$releasever-$basearch/
    skip_if_unavailable: True
    gpgcheck: 1
    gpgkey: https://copr-be.cloud.fedoraproject.org/results/mmu/credstash-rpm/pubkey.gpg
    repo_gpgcheck: 0
    enabled: 1

- become: True
  tags: extdep
  dnf:
    name:
      - awscli
      - python3-dns
      - python3-boto3
      - python3-credstash
      - certbot-dns-route53

- become: True
  tags: extdep
  dnf:
    name:
      - patch

- become: True
  patch:
    dest: /usr/lib/python3.7/site-packages/boto/connection.py
    src: boto_connection.patch

- become: True
  copy:
    dest: /etc/profile.d/aws.sh
    content: |
      complete -C /usr/bin/aws_completer aws

- import_role:
    role: proxy
  vars:
    proxy_ca_files:
      - /usr/lib/python3.7/site-packages/botocore/cacert.pem
      - /usr/lib/python3.7/site-packages/boto/cacerts/cacerts.txt
  when: lookup('env', 'http_proxy')
