set nocompatible              " be iMproved, required
filetype off                  " required

" set the runtime path to include Vundle and initialize
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()
" alternatively, pass a path where Vundle should install plugins
"call vundle#begin('~/some/path/here')

" let Vundle manage Vundle, required
Plugin 'VundleVim/Vundle.vim'

" The following are examples of different formats supported.
" Keep Plugin commands between vundle#begin/end.
" plugin on GitHub repo
"Plugin 'tpope/vim-fugitive'
" plugin from http://vim-scripts.org/vim/scripts.html
" Plugin 'L9'
" Git plugin not hosted on GitHub
"Plugin 'git://git.wincent.com/command-t.git'
" git repos on your local machine (i.e. when working on your own plugin)
"Plugin 'file:///home/gmarik/path/to/plugin'
" The sparkup vim script is in a subdirectory of this repo called vim.
" Pass the path to set the runtimepath properly.
"Plugin 'rstacruz/sparkup', {'rtp': 'vim/'}
" Install L9 and avoid a Naming conflict if you've already installed a
" different version somewhere else.
" Plugin 'ascenator/L9', {'name': 'newL9'}

"Plugin 'davidhalter/jedi-vim'
Plugin 'michaeljsmith/vim-indent-object'
"Plugin 'godlygeek/tabular'
Plugin 'junegunn/vim-easy-align'
Plugin 'pearofducks/ansible-vim'
"Plugin 'dhruvasagar/vim-table-mode'
"Plugin 'chrisbra/csv.vim'
"Plugin 'racer-rust/vim-racer'
Plugin 'chr4/nginx.vim'
Plugin 'chr4/sslsecure.vim'
Plugin 'ambv/black'

" All of your Plugins must be added before the following line
call vundle#end()            " required
filetype plugin indent on    " required
" To ignore plugin indent changes, instead use:
"filetype plugin on
"
" Brief help
" :PluginList       - lists configured plugins
" :PluginInstall    - installs plugins; append `!` to update or just :PluginUpdate
" :PluginSearch foo - searches for foo; append `!` to refresh local cache
" :PluginClean      - confirms removal of unused plugins; append `!` to auto-approve removal
"
" see :h vundle for more details or wiki for FAQ
" Put your non-Plugin stuff after this line

let g:ansible_options = {'ignore_blank_lines': 0}

set switchbuf=usetab

set wildmode=longest,list,full
set wildmenu
set hidden

set expandtab
set tabstop=4
set shiftwidth=4

map ZZ :mksession! ~/.vimsession.vim<CR>:xa<CR>

if &diff
    syntax off
endif

if argc() >= 1 && argv()[0] =~ 'roles/.*/$'
	echo 'role mode: '
	set suffixesadd=.yml
	let x = argv()[0]
	execute 'args' join(glob(x.'{tasks,defaults,vars,meta,handlers}/*.yml', 0, 1))
  execute 'cd' x
	set path+=files/**
	set path+=templates/**
endif

if argc() >= 1 && argv()[0] =~ '^inv'
	set path+=./host_vars/
	set path+=./group_vars/
	set path+=./*/host_vars/
	set path+=./*/group_vars/
	set isfname+=@-@
	set suffixesadd=.yml
endif

"execute pathogen#infect()
"let vim_markdown_preview_browser='Mozilla Firefox'
"let vim_markdown_preview_perl=1
"let vim_markdown_preview_use_xdg_open=1
"let g:table_mode_corner="|"

let g:racer_cmd="/home/muenchm/.cargo/bin/racer"
let $RUST_SRC_PATH="/home/muenchm/rust-bare-metal/src/bin"
"let g:racer_experimental_completer = 1

set path+=**
